CREATE TABLE IF NOT EXISTS USERS (
    UserID   INT PRIMARY KEY,
    FullName VARCHAR(100),
    Phone    INT
);

ALTER TABLE USERS
MODIFY COLUMN Phone VARCHAR(15);

UPDATE USERS
SET Phone = LPAD(Phone, 10, '0')
WHERE UserID > 0;

SELECT * FROM USERS;